### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by rickdg** [matthiaswh/budgeterbium#2]
After running this app I only see routing for Accounts and Budgets. What's happening with Transactions?
I didn't read the whole tutorial, so I don't know if that was ever added?

**Comment by joshuamabina** [comment]
> This is part 12 of an 18 part series titled [Vue.js Application Tutorial - Creating a Simple Budgeting App with Vue](http://matthiashager.com/complete-vuejs-application-tutorial/planning-transactions). It is highly recommended that you read the series in order, as each section builds on the last.

> The next entry is expected to be published on 26 May 2017

**Comment by rickdg** [comment]
Sorry about that.

**Comment by matthiaswh** [comment]
It's still a work in progress. I got behind schedule for this last section, but you should be able to pull the latest commit now with the Transactions module. The next step of the tutorial will be published soon, and then I'll work on some quality of life / fixes.
